version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: chitthi_app
        ports:
            - "${PORT:-8080}:${PORT:-8080}" # fallback to 8080 if not defined
        depends_on:
            - redis
            - db
        env_file:
            - .env
        volumes:
            - .:/app
        restart: unless-stopped

    redis:
        image: redis:7
        container_name: chitthi_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        restart: unless-stopped

    db:
        image: postgres:15
        container_name: chitthi_db
        ports:
            - "5432:5432"
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    redis_data:
    postgres_data:
