version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: chitthi_app
        ports:
            - "8080:8080"
        depends_on:
            - redis
            - db
        env_file:
            - .env
        volumes:
            - .:/app
        restart: unless-stopped

    redis:
        image: redis:7
        container_name: chitthi_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        restart: unless-stopped

    db:
        image: postgres:15
        container_name: chitthi_db
        ports:
            - "5432:5432"
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    redis_data:
    postgres_data:
